firstName = input("What is your first name?: ")
secondName = input("And your second name: ")
print("Hello ", firstName, secondName)
print()
print("What do you call a bear with no teeth?\nGummy Bear LOLZ",)
print()
num1 = int(input("Lets do some maths, enter a number: "))
num2 = int(input("Enter a second number: "))
print(num1," + ", num2, " = ", num1+num2)
print()
num1 = int(input("Let's make it more complicated, Enter a number: "))
num2 = int(input("Enter another number: "))
num3 = int(input("And one more: "))
print(num1, " + ", num2, " x ", num3, " = ", (num1 + num2) * num3)
print()
pizza = int(input("How many slices of pizza did you start with: "))
pizzaEaten = int(input("How many slices of pizza have you eaten: "))
print("You have ", pizza - pizzaEaten, " slices left.")
print()
age = int(input("What is you age? "))
print("After your next birthday you will be ", age + 1)
print()
bill = int(input("What is the total price of the bill?: "))
diners = int(input("How many diners are there?: "))
print("That will be ", bill / diners," per person.")
print()
days = int(input("How many days are there?: "))
print("In ", days, "'s there are ", "This is equivaelnt to ", days * 24, " days, ", days * (24 * 60), " minutes, and ", (days * (24 * ( 60 * 60 ))))
print()
weight = int(input("Enter a weight in Kg and i'll convert it into pounds: "))
pounds = int(weight * 2204)
print(weight,"kgs is ", pounds, " pounds." )
print()
userNum1 = int(input("Enter a number over 100: "))
userNum2 = int(input("Enter a number under 10: "))
print(userNum2, " goes into ", userNum1, ", ", userNum1 // userNum2, " times")
